// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoYmLbB8o6BAWVwr0lO6aEJoQ98B1g3a8',
    appId: '1:299718454090:web:68cd98ade4fb43fbfeafb3',
    messagingSenderId: '299718454090',
    projectId: 'expiration-date-reminde',
    authDomain: 'expiration-date-reminde.firebaseapp.com',
    databaseURL: 'https://expiration-date-reminde-default-rtdb.firebaseio.com',
    storageBucket: 'expiration-date-reminde.appspot.com',
    measurementId: 'G-VC2B7JXRMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKvk9Ux6oOtHh5H43vikOG3ER41K6fPEA',
    appId: '1:299718454090:android:a9b21fc4d5ac45e1feafb3',
    messagingSenderId: '299718454090',
    projectId: 'expiration-date-reminde',
    databaseURL: 'https://expiration-date-reminde-default-rtdb.firebaseio.com',
    storageBucket: 'expiration-date-reminde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwdnUtrfGN-8r2LsFF3axZraOoaDxE0Rs',
    appId: '1:299718454090:ios:7b0227c884872775feafb3',
    messagingSenderId: '299718454090',
    projectId: 'expiration-date-reminde',
    databaseURL: 'https://expiration-date-reminde-default-rtdb.firebaseio.com',
    storageBucket: 'expiration-date-reminde.appspot.com',
    androidClientId: '299718454090-f0tgcerr5b8a6i4gdujc26l3o67fm3i9.apps.googleusercontent.com',
    iosClientId: '299718454090-7k1lfl0t6c781hng1pccvhddlie6ukkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.expirationDateReminde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwdnUtrfGN-8r2LsFF3axZraOoaDxE0Rs',
    appId: '1:299718454090:ios:feb64f315f961679feafb3',
    messagingSenderId: '299718454090',
    projectId: 'expiration-date-reminde',
    databaseURL: 'https://expiration-date-reminde-default-rtdb.firebaseio.com',
    storageBucket: 'expiration-date-reminde.appspot.com',
    androidClientId: '299718454090-f0tgcerr5b8a6i4gdujc26l3o67fm3i9.apps.googleusercontent.com',
    iosClientId: '299718454090-sntf0osop79nb2nqulq9gbov9tupe6ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.expirationDateReminde.RunnerTests',
  );
}
